# This workflow uploads markdown documents to Meilisearch when code is merged to test branch

name: 测试环境-上传到Meilisearch

on:
  push:
    branches: [test]
  workflow_dispatch:

jobs:
  upload-to-meilisearch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install required tools
        run: |
          # Update package list and install jq if not available
          sudo apt-get update
          sudo apt-get install -y jq
          
          # Verify all required tools are available
          echo "Checking required tools..."
          jq --version
          curl --version
          openssl version
          echo "All required tools are available."

      - name: Validate environment variables
        run: |
          if [[ -z "$MEILI_ENDPOINT" || -z "$MEILI_API_KEY" || -z "$MEILI_INDEX" ]]; then
            echo "Error: Missing required environment variables."
            echo "Please ensure MEILI_ENDPOINT, MEILI_API_KEY, and MEILI_INDEX are set."
            exit 1
          fi
          echo "Environment variables validated successfully."
        env:
          MEILI_ENDPOINT: ${{ secrets.MEILI_ENDPOINT_TEST }}
          MEILI_API_KEY: ${{ secrets.MEILI_API_KEY_TEST }}
          MEILI_INDEX: ${{ secrets.MEILI_INDEX_TEST }}

      - name: Upload documents to Meilisearch
        run: |
          chmod +x ./upload.sh
          ./upload.sh
        env:
          MEILI_ENDPOINT: ${{ secrets.MEILI_ENDPOINT_TEST }}
          MEILI_API_KEY: ${{ secrets.MEILI_API_KEY_TEST }}
          MEILI_INDEX: ${{ secrets.MEILI_INDEX_TEST }}

      - name: Upload summary
        if: always()
        run: |
          echo "Meilisearch upload workflow completed."
          echo "Check the logs above for detailed results."
